/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg123210061_kuis;

import java.awt.event.ActionEvent;
import javax.swing.JButton;

/**
 *
 * @author Lab Informatika
 */
public class mainMenu extends javax.swing.JFrame {
    
    /**
     * Creates new form mainMenu
     */
    public mainMenu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        segitigaButton = new javax.swing.JButton();
        lingkaranButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        segitigaButton.setText("Segitiga");
        segitigaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segitigaButtonActionPerformed(evt);
            }
        });

        lingkaranButton.setText("Lingkaran");
        lingkaranButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lingkaranButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(segitigaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(lingkaranButton)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(logoutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(segitigaButton)
                    .addComponent(lingkaranButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void segitigaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segitigaButtonActionPerformed
        // TODO add your handling code here:
        segitigaAction(evt);
    }//GEN-LAST:event_segitigaButtonActionPerformed

    private void lingkaranButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lingkaranButtonActionPerformed
        // TODO add your handling code here:
        lingkaranAction(evt);
    }//GEN-LAST:event_lingkaranButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        logoutAction(evt);
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton lingkaranButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton segitigaButton;
    // End of variables declaration//GEN-END:variables

    private void segitigaAction(ActionEvent evt) {
        //memilih menu segitiga
        new segitigaPage().setVisible(true);
        this.dispose();//To change body of generated methods, choose Tools | Templates.
    }

    private void lingkaranAction(ActionEvent evt) {
        //memilih menu lingkaran
        new lingkaranPage().setVisible(true);
        this.dispose(); //To change body of generated methods, choose Tools | Templates.
    }

    private void logoutAction(ActionEvent evt) {
        //kembali ke login
        new loginPage().setVisible(true);
        this.dispose(); //To change body of generated methods, choose Tools | Templates.
    }
}
